### ISSUE TITLE
Overrides are not getting installed

### ISSUE THREAD

**Issue by joemash** [PatrickKoss/NvChad-Custom-Config#1]
On running of the below command, it runs successfully without issues but :

Only the `lua-language-server` is getting installed

All the other packages inside plugins/overrides.lua are being skipped

command being run
`git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && git clone https://github.com/PatrickKoss/NvChad-Custom-Config.git ~/.config/nvim/lua/custom --depth 1 && `nvim`

The below are the versions of the system

+ Ubuntu 22.04 jammy
+ NVIM v0.9.4
+ Mason 1.8.3

**Comment by deepnet-devs** [comment]
i have the same issue !!!

**Comment by PatrickKoss** [comment]
Hey @deepnet-devs and @joemash 

The config was broken with an update of nvchad. I did some changes which now work on my machine. Can you try setting it up again? By removing the config you get a clean start:

```
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
```

and then run the clone command again. On the other hand a git pull in ~/.config/nvim/lua/custom should also work.
Feel free to report back if it works or still does not.

Best regards,
Patrick

**Comment by deepnet-devs** [comment]
@PatrickKoss thank you it's a good job 👍🏻

**Comment by PatrickKoss** [comment]
Since it works I will close the issue.
