### ISSUE TITLE
Invalid import spec

### ISSUE THREAD

**Issue by iamenderst** [PatrickKoss/NvChad-Custom-Config#4]
```
Error detected while processing /home/enderst/.config/nvim/init.lua:
Invalid import spec. `import` should be a string: {
  import = { { "neovim/nvim-lspconfig",
      config = <function 1>
    }, { "nvim-treesitter/nvim-treesitter",
      opts = {
```
Must be some changes coming down with NVIM v0.10.0-dev

**Comment by PatrickKoss** [comment]
Hey @iamenderst ,
I am not sure why it happens. Probably with nvim 0.9.5 this behavior occurs. In #2 I mentioned a quick fix. So, previously the default plugin list and the custom plugin list was merged with the table insert function. But now the behavior changed. I think we need to do a pr on nvchad to fix it for the latest nvim versions.

**Comment by PatrickKoss** [comment]
Updated the readme for the future
